name = "backend"
compatibility_date = "2024-08-21"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDAxZjUyMjUtMzYxMS00Y2ZiLTk4MTUtZTI2ZTVkYWQyZDBhIiwidGVuYW50X2lkIjoiN2U5OTk4MmVjMzMzNTliNjc2MzdjYjY1Yjk4NTE3NzM2NTU3NjlkZGJlZGZmMGI4ZDFhZTNhMmI2YTQzMjU0MSIsImludGVybmFsX3NlY3JldCI6IjUyNTQ2YzMyLWY5OWMtNGIzMi04MDFmLTJhZDQzMDRjYzQ5MyJ9.8Pl7rg4fAIniVJs0tK38fBGaeeyqXT_fK-wa2YLzZ74"

JWT_SECRET="mukulhere"